resources:
- name: repo
  type: git
  check_every: 3m
  source:
    uri: https://github.com/vavere/cc-make

jobs:
- name: make
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: build
    config:
      platform: windows
      inputs:
      - name: repo
      outputs:
      - name: result
      params:
        PNAME: product
        REPO: \\s1\install\servers\MA-1
        BUILD: 1
        OUTPUT: ..\result
      run:
        dir: repo
        path: make.bat
  - task: deploy
    config:
      platform: windows
      inputs:
      - name: repo
      - name: result
      params:
        PNAME: product
        REPO: \\s1\install\servers\MA-1
        TARGET: \\s1
      run:
        path: psexec
        args:
        - -accepteula
        - -nobanner
        - \\s1      
        - -d 
        - -s 
        - cmd
        - /c
        - msiexec /i %REPO%\%PNAME%.msi /l*vx %REPO%\%PNAME%.log /qb
      
