resource_types:
- name: smb-resource
  type: docker-image
  source:
      repository: vavere/concourse-smb-share
      tag: "1.4"

resources:
- name: repo
  type: git
  check_every: 3m
  source:
    uri: https://github.com/vavere/cc-make

- name: s1
  type: smb-resource
  source:
    path: //192.168.1.9/install/servers/test
    user: ((user))
    pass: ((pass))
    in: false

jobs:
- name: make
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: build
    config:
      platform: windows
      inputs:
      - name: repo
      outputs:
      - name: result
      params:
        PNAME: product
        BUILD: 1
        OUTPUT: ../result
      run:
        dir: repo
        path: make.bat
  - task: dir
    config:
      platform: windows
      inputs:
      - name: result
      run:
        path: cmd
        args:
        - /c
        - dir
  - put: result
    resource: s1
    params:
      files:
      - result/product.msi
  # params:
  #   files:
  #   - product.msi
  # - task: deliver
  #   config:
  #     platform: windows
  #     inputs:
  #     - name: result
  #     run:
  #       path: cmd
  #       args:
  #       - /c
  #       - copy result\* \\s1\install\servers\MA-1\
  # - task: deploy
  #   config:
  #     platform: windows
  #     run:
  #       path: psexec
  #       args:
  #       - -accepteula
  #       - -nobanner
  #       - \\s1      
  #       - -s 
  #       - cmd
  #       - /c
  #       - msiexec /i \\s1\install\servers\MA-1\product.msi /l*vx \\s1\install\servers\MA-1\product.log /qb
      
