resources:
- name: repo
  type: git
  check_every: 3m
  source:
    uri: https://github.com/vavere/cc-make

jobs:
- name: make
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: build
    config:
      platform: windows
      inputs:
      - name: repo
      outputs:
      - name: result
      params:
        PNAME: product
        REPO: \\s1\install\servers\MA-1
        BUILD: 1
        OUTPUT: ..\result
      run:
        dir: repo
        path: make.bat
  - task: deliver
    config:
      platform: windows
      inputs:
      - name: result
      run:
        path: cmd
        args:
        - /c
        - copy result\*.msi \\s1\install\servers\MA-1\
  - task: deploy
    config:
      platform: windows
      run:
        path: psexec
        args:
        - -accepteula
        - -nobanner
        - \\s1      
        - -s 
        - cmd
        - /c
        - msiexec /i \\s1\install\servers\MA-1\product.msi /l*vx \\s1\install\servers\MA-1\product.log /qb
      
