resources:
- name: repo
  type: git
  check_every: 3m
  source:
    uri: https://github.com/vavere/cc-make

jobs:
- name: make
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: build
    config:
      platform: windows
      inputs:
      - name: repo
      outputs:
      - name: result
      params:
        PNAME: product
        PID: 72e712cb-3c01-44c5-b4a4-43e1524fc8f3
        BUILD: 1
        OUTPUT: ..\result
      run:
        dir: repo
        path: make.bat
  - task: deploy
    config:
      platform: windows
      inputs:
      - name: result
      run:
        dir: result
        path: cmd
        args:
        - /c
        - dir
      
