resources:
- name: repo
  type: git
  check_every: 3m
  source:
    uri: https://github.com/vavere/cc-task

jobs:
- name: make
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: build
    config:
      platform: windows
      inputs:
      - name: repo
      params:
        PNAME: product
        PID: 72e712cb-3c01-44c5-b4a4-43e1524fc8f3
        BUILD: 1
        DEPLOY: \\\\s1.ma-1.lv\\install\\servers\\MA-1
      run:
        dir: repo
        path: make.bat
      
