resources:
- name: repo
  type: git
  check_every: 3m
  source:
    uri: https://github.com/vavere/cc-task

jobs:
- name: make
  serial: true
  plan:
  - get: repo
    trigger: true
  - task: build
    config:
      platform: windows
      inputs:
      - name: repo
      run:
        dir: repo
        path: make.bat
      
